---
# tasks file for apigee-opdk-setup-os

- name: Configure AWS AMI OS package manager repositories for Apigee
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"
  when: ansible_bios_version | lower | search('amazon') and ansible_os_family | lower == 'redhat' and ansible_distribution_major_version | version_compare('6', '>')

# TODO: Look up the ansible_distribution name for RHEL systems
#- name: If using RHEL then register RHEL on RHN
#  shell: "subscription-manager register --username={{ rhel_user_name }} --password={{ rhel_password }} --auto-attach"
#  when: ansible_bios_version | lower | search('amazon') and ansible_os_family | lower == 'redhat' and ansible_distribution_major_version | version_compare('7', '>')

- name: Enable Yum repositories
  yum_repository:
     enabled: yes
     state: present
     name: "{{ items.name }}"
     baseurl: "{{ items.baseurl }}"
     file: 'redhat'
  with_items: "{{ vz_aws_rhel7_repositories }}"

- name: Yum clean
  become: yes
  shell: "yum clean all"

- name: Create pip config folder
  file:
    path: "{{ pip_conf_dir }}"
    state: directory
  when: pip_conf_dir is defined

- name: Configure pip
  template:
    src: pip.conf.j2
    dest: "{{ pip_conf_dir }}/pip.conf"
  when: pip_conf_dir is defined and pip_index_url is defined

- name: Do not use proxy definitions
  include: with_no_proxy.yml
  when: http_proxy is not defined and https_proxy is not defined

- name: Use proxy definitions
  include: with_proxy.yml
  when: http_proxy is defined and https_proxy is defined

- name: Update python packages
  become: yes
  pip:
    name: '{{ item }}'
    state: present
  with_items: "{{ pip_packages }}"

