---
# tasks file for apigee-opdk-setup-os
- name: Collect setup facts
  setup:

- block:

  - name: Collect EC2 facts
    ec2_facts:

#  - name: Collect EC2 remote facts
#    ec2_remote_facts:
#      aws_access_key: '{{ aws_access_key_id }}'
#      aws_secret_key: '{{ aws_secret_access_key }}'
#      region: '{{ secure_aws_region }}'

  when: ansible_bios_version is defined and ansible_bios_version | lower | search('amazon')

- name: Yum clean
  become: yes
  shell: yum clean all

- block:

  - name: Add yum centos-releas-SCL repository for CentOS 6
    become: yes
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - centos-release-SCL
    when: ansible_distribution | lower == "centos"
    tags:
    - epel

  - name: Add yum epel repository for Redhat/CentOS 6.x
    become: yes
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - '{{ epel_rhel6 }}'
    tags:
    - epel

  when: ansible_distribution_major_version is defined and ansible_distribution_major_version | version_compare('7', '<')

- block:

  - name: Add yum epel repository for Redhat/CentOS 7.x
    ignore_errors: yes
    become: yes
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - '{{ epel_rhel7 }}'
    tags:
    - epel

  when: ansible_distribution_major_version is defined and ansible_distribution_major_version | version_compare('7', '>=')

- name: Proactively remove qpid packages that cause yum update failures, ignore errors
  become: yes
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
  - apigee-qpidd-*
  - qpid-*
  - python-qpid*
  - libqpid*
  ignore_errors: true

#- name: Keep yum downloads small
#  become: yes
#  yum:
#    name: "{{ item }}"
#    state: present
#  with_items:
#  - deltarpm
#  register: yum_status
#  tags:
#  - epel

#- name: Speed up yum
#  become: yes
#  shell: yum makecache {{ item }}
#  with_items:
#  - yum-presto
#  - fast
#  when: yum_status.changed
#  register: yum_status
#  tags:
#  - epel

- name: Update basic yum os packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bind-utils
  - chkconfig
  - curl
  - tar
  - wget
  - yum-utils
  - unzip
  - rsync
  - which
  - libselinux-python
  - nss
  - openssh-clients
  - openssh-server
  - sudo
  - grep
  - rpm
  - rng-tools
  - sed
  - unzip

- name: Start rngd service
  service:
    name: rngd
    enabled: yes
    state: started

- name: Update vm.swappiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: '{{ vm_swappiness }}'
    state: present
  tags:
  - os_tuning

- name: Disable Default IPV6
  become: yes
  shell: "sysctl -w net.ipv6.conf.default.disable_ipv6=1"

- name: Disable All IPV6
  become: yes
  shell: "sysctl -w net.ipv6.conf.all.disable_ipv6=1"

- name: Update for apigee installation environment
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export CONTINUE_ON_WARNING="
    line: 'export CONTINUE_ON_WARNING={{ apigee_continue_on_warning }}'
    backup: yes

- name: Add pip package manager
  become: yes
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  tags:
  - pip

- name: Install pip package manager
  become: yes
  shell: python /tmp/get-pip.py
  tags:
  - pip

- name: Update python packages
  become: yes
  tags:
  - pip
  register: pip_status
  pip:
    name: '{{ item }}'
    state: present
  with_items:
  - httplib2
  - pexpect
  - passlib
  - requests
  - kazoo
