---
# tasks file for apigee-opdk-setup-os
- name: Yum clean
  become: yes
  shell: "yum clean all"

- name: Create pip config folder
  file:
    path: "{{ pip_conf_dir }}"
    state: directory
  when: pip_conf_dir is defined

- name: Configure pip
  template:
    src: pip.conf.j2
    dest: "{{ pip_conf_dir }}/pip.conf"
  when: pip_conf_dir is defined and pip_index_url is defined

- name: Do not use proxy definitions
  include: with_no_proxy.yml
  when: (https_proxy is not defined or https_proxy | trim == '') and (http_proxy is not defined or http_proxy | trim == '') and (no_proxy is not defined or no_proxy | trim == '')

- name: Use proxy definitions
  include: with_proxy.yml
  when: (https_proxy is defined or https_proxy | trim != '') and (http_proxy is defined or http_proxy | trim != '') and (no_proxy is defined or no_proxy | trim == '')

- name: Update System Entropy Settings
  lineinfile:
    backrefs: yes
    path: /usr/lib/systemd/system/rngd.service
    regexp: '^(ExecStart=/sbin/rngd -f)'
    line: '\1 -r /dev/urandom'

- name: Daemon Reload
  shell: /usr/bin/systemctl daemon-reload

- name: Start rngd service
  service:
    name: rngd
    enabled: yes
    state: restarted

- name: Update vm.swappiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: '{{ vm_swappiness }}'
    state: present

- name: Disable Default IPV6
  become: yes
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_set: yes
  tags: ['ipv6']

- name: Disable All IPV6
  become: yes
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
  tags: ['ipv6']

- name: Update for apigee installation environment with no proxy
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export CONTINUE_ON_WARNING="
    line: 'export CONTINUE_ON_WARNING={{ apigee_continue_on_warning }}'
    backup: yes
