---
# tasks file for apigee-opdk-setup-os
- name: Update basic yum os packages
  import_role:
    name: apigee-opdk-setup-os-epel
  vars:
    yum_os_minimum_packages: "{{ yum_packages }}"

#- name: Do not use proxy definitions
#  include: with_no_proxy.yml
#  when: http_proxy is not defined and https_proxy is not defined
#
#- name: Use proxy definitions
#  include: with_proxy.yml
#  when: http_proxy is defined and https_proxy is defined

- name: Remove IPv6 localhost entry
  become: yes
  replace:
    dest: /etc/hosts
    regexp: '(^::1.*localhost6.*)$'
    replace: '# \1'

- block:
  - name: Start rngd service
    service:
      name: rngd
      enabled: yes
      state: started

  - name: Patch rngd service unit
    replace:
      dest: /usr/lib/systemd/system/rngd.service
      regexp: ^(ExecStart=/sbin/rngd -f)$
      replace: \1 -r /dev/urandom
    register: rngd_unit

  - name: Reload systemd
    command: systemctl daemon-reload
    when: rngd_unit.changed

  - name: Restart and enable rngd
    service:
      name: rngd
      state: restarted
      enabled: yes
    when: rngd_unit.changed

  - name: Start and enable rngd
    service:
      name: rngd
      state: started
      enabled: yes
    when: not rngd_unit.changed
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | version_compare("6", ">")

- name: Update vm.swappiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: '{{ vm_swappiness }}'
    state: present

- name: Disable All IPV6
  tags: ['ipv6']
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present
    sysctl_set: yes

- name: Disable All IPV6
  tags: ['ipv6']
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    state: present
    sysctl_set: yes

- name: Update for apigee installation environment
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export CONTINUE_ON_WARNING="
    line: 'export CONTINUE_ON_WARNING={{ apigee_continue_on_warning }}'
    backup: yes
