---
---
# tasks file for apigee-opdk-setup-os
- name: Update basic yum os packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bind-utils
  - chkconfig
  - curl
  - tar
  - wget
  - yum-utils
  - unzip
  - rsync
  - which
  - libselinux-python
  - nss
  - openssh-clients
  - openssh-server
  - grep
  - rpm
  - rng-tools
  - sed
  - unzip

- name: Download pip package manager
  become: yes
  tags: ['pip-manager']
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: pip_conf_dir is not defined

- name: Install pip package manager
  become: yes
  tags: ['pip-manager']
  shell: python /tmp/get-pip.py
  when: pip_conf_dir is not defined

- name: Update python packages
  become: yes
  pip:
    name: '{{ item }}'
    state: present
  with_items:
  - httplib2
  - pexpect
  - passlib
  - requests
  - kazoo
