---
- name: Yum update with proxy
  yum:
    name: '*'
    state: latest
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Update basic yum os packages with proxy
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

