---
# tasks file for apigee-opdk-setup-os
#- name: Update EPEL with no proxy
#  yum:
#    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
#    state: present
#  when: epel_repo is not defined and epel_repo | trim != ''

- name: Yum update with no proxy
  yum:
    name: '*'
    state: latest

#- name: Update EPEL from custom location with no proxy
#  yum:
#    name: "{{ epel_repo }}"
#    state: present
#  when: epel_repo is defined and epel_repo | trim != ''

- name: Update basic yum os packages with no proxy
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_os_minimum_packages }}"

- name: Download pip package manager with no proxy
  become: yes
  tags: ['pip-manager']
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: pip_conf_dir is not defined

- name: Install pip package manager with no proxy
  become: yes
  tags: ['pip-manager']
  shell: python /tmp/get-pip.py
  when: pip_conf_dir is not defined

- name: Update python packages with no proxy
  become: yes
  pip:
    name: '{{ item }}'
    state: present
  with_items: "{{ pip_packages }}"
